// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
)

const CreateUser = `-- name: CreateUser :exec
INSERT INTO users (id, full_name, email, role)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, CreateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Role,
	)
	return err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users where id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, DeleteUser, id)
	return err
}

const ListById = `-- name: ListById :one
select id, full_name, email, role, created_at, updated_at, deleted_at from users where id = ?
`

func (q *Queries) ListById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, ListById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListUsers = `-- name: ListUsers :many
select id, full_name, email, role, created_at, updated_at, deleted_at from users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateUser = `-- name: UpdateUser :exec
update users set full_name = ?, email = ? where id = ?
`

type UpdateUserParams struct {
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, UpdateUser, arg.FullName, arg.Email, arg.ID)
	return err
}
